# Generated by Django 5.1.3 on 2024-11-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Product_Review', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
