# Generated by Django 5.1.3 on 2024-11-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Product_Review', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
